=== JoeAlisson/Server-Interlude/Datapack/data/xml/schema/classInfo.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:element name="classInfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="level" type="LevelInfo"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="classId" type="xs:int" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="classLevel" type="xs:int" use="required"/>
            <xs:attribute name="parent" type="xs:int" default="-1"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="LevelInfo">
        <xs:sequence/>
        <xs:attribute name="value" type="xs:int" use="required"/>
        <xs:attribute name="hp" type="xs:float" use="required"/>
        <xs:attribute name="mp" type="xs:float" use="required"/>
        <xs:attribute name="cp" type="xs:float" use="required"/>
        <xs:attribute name="hpRegen" type="xs:float" use="required"/>
        <xs:attribute name="mpRegen" type="xs:float" use="required"/>
        <xs:attribute name="cpRegen" type="xs:float" use="required"/>
    </xs:complexType>

</xs:schema>

=== JoeAlisson/Server-Interlude/Datapack/data/xml/classes/Cleric.xml
<?xml version='1.0' encoding='utf-8'?>

<classInfo classId="15" name="Cleric" classLevel="20" parent="10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../schema/classInfo.xsd">
    <level value="20" hp="424.0" mp="192.0" cp="212.0" hpRegen="3.4" mpRegen="1.2" cpRegen="2.5" />
    <level value="21" hp="458.1" mp="205.2" cp="229.05" hpRegen="3.5" mpRegen="1.5" cpRegen="3.5" />
    <level value="22" hp="492.51" mp="218.52" cp="246.255" hpRegen="3.6" mpRegen="1.5" cpRegen="3.5" />
    <level value="23" hp="527.23" mp="231.96" cp="263.615" hpRegen="3.7" mpRegen="1.5" cpRegen="3.5" />
    <level value="24" hp="562.26" mp="245.52" cp="281.13" hpRegen="3.8" mpRegen="1.5" cpRegen="3.5" />
    <level value="25" hp="597.6" mp="259.2" cp="298.8" hpRegen="3.9" mpRegen="1.5" cpRegen="3.5" />
    <level value="26" hp="633.25" mp="273.0" cp="316.625" hpRegen="4.0" mpRegen="1.5" cpRegen="3.5" />
    <level value="27" hp="669.21" mp="286.92" cp="334.605" hpRegen="4.1" mpRegen="1.5" cpRegen="3.5" />
    <level value="28" hp="705.48" mp="300.96" cp="352.74" hpRegen="4.2" mpRegen="1.5" cpRegen="3.5" />
    <level value="29" hp="742.06" mp="315.12" cp="371.03" hpRegen="4.3" mpRegen="1.5" cpRegen="3.5" />
    <level value="30" hp="778.95" mp="329.4" cp="389.475" hpRegen="4.4" mpRegen="1.5" cpRegen="3.5" />
    <level value="31" hp="816.15" mp="343.8" cp="408.075" hpRegen="4.5" mpRegen="1.8" cpRegen="4.5" />
    <level value="32" hp="853.66" mp="358.32" cp="426.83" hpRegen="4.6" mpRegen="1.8" cpRegen="4.5" />
    <level value="33" hp="891.48" mp="372.96" cp="445.74" hpRegen="4.7" mpRegen="1.8" cpRegen="4.5" />
    <level value="34" hp="929.61" mp="387.72" cp="464.805" hpRegen="4.8" mpRegen="1.8" cpRegen="4.5" />
    <level value="35" hp="968.05" mp="402.6" cp="484.025" hpRegen="4.9" mpRegen="1.8" cpRegen="4.5" />
    <level value="36" hp="1006.8" mp="417.6" cp="503.4" hpRegen="5.0" mpRegen="1.8" cpRegen="4.5" />
    <level value="37" hp="1045.86" mp="432.72" cp="522.93" hpRegen="5.1" mpRegen="1.8" cpRegen="4.5" />
    <level value="38" hp="1085.23" mp="447.96" cp="542.615" hpRegen="5.2" mpRegen="1.8" cpRegen="4.5" />
    <level value="39" hp="1124.91" mp="463.32" cp="562.455" hpRegen="5.3" mpRegen="1.8" cpRegen="4.5" />
    <level value="40" hp="1164.9" mp="478.8" cp="582.45" hpRegen="5.4" mpRegen="1.8" cpRegen="4.5" />
    <level value="41" hp="1205.2" mp="494.4" cp="602.6" hpRegen="5.5" mpRegen="2.1" cpRegen="5.5" />
    <level value="42" hp="1245.81" mp="510.12" cp="622.905" hpRegen="5.6" mpRegen="2.1" cpRegen="5.5" />
    <level value="43" hp="1286.73" mp="525.96" cp="643.365" hpRegen="5.7" mpRegen="2.1" cpRegen="5.5" />
    <level value="44" hp="1327.96" mp="541.92" cp="663.98" hpRegen="5.8" mpRegen="2.1" cpRegen="5.5" />
    <level value="45" hp="1369.5" mp="558.0" cp="684.75" hpRegen="5.9" mpRegen="2.1" cpRegen="5.5" />
    <level value="46" hp="1411.35" mp="574.2" cp="705.675" hpRegen="6.0" mpRegen="2.1" cpRegen="5.5" />
    <level value="47" hp="1453.51" mp="590.52" cp="726.755" hpRegen="6.1" mpRegen="2.1" cpRegen="5.5" />
    <level value="48" hp="1495.98" mp="606.96" cp="747.99" hpRegen="6.2" mpRegen="2.1" cpRegen="5.5" />
    <level value="49" hp="1538.76" mp="623.52" cp="769.38" hpRegen="6.3" mpRegen="2.1" cpRegen="5.5" />
    <level value="50" hp="1581.85" mp="640.2" cp="790.925" hpRegen="6.4" mpRegen="2.1" cpRegen="5.5" />
    <level value="51" hp="1625.25" mp="657.0" cp="812.625" hpRegen="6.5" mpRegen="2.4" cpRegen="6.5" />
    <level value="52" hp="1668.96" mp="673.92" cp="834.48" hpRegen="6.6" mpRegen="2.4" cpRegen="6.5" />
    <level value="53" hp="1712.98" mp="690.96" cp="856.49" hpRegen="6.7" mpRegen="2.4" cpRegen="6.5" />
    <level value="54" hp="1757.31" mp="708.12" cp="878.655" hpRegen="6.8" mpRegen="2.4" cpRegen="6.5" />
    <level value="55" hp="1801.95" mp="725.4" cp="900.975" hpRegen="6.9" mpRegen="2.4" cpRegen="6.5" />
    <level value="56" hp="1846.9" mp="742.8" cp="923.45" hpRegen="7.0" mpRegen="2.4" cpRegen="6.5" />
    <level value="57" hp="1892.16" mp="760.32" cp="946.08" hpRegen="7.1" mpRegen="2.4" cpRegen="6.5" />
    <level value="58" hp="1937.73" mp="777.96" cp="968.865" hpRegen="7.2" mpRegen="2.4" cpRegen="6.5" />
    <level value="59" hp="1983.61" mp="795.72" cp="991.805" hpRegen="7.3" mpRegen="2.4" cpRegen="6.5" />
    <level value="60" hp="2029.8" mp="813.6" cp="1014.9" hpRegen="7.4" mpRegen="2.4" cpRegen="6.5" />
    <level value="61" hp="2076.3" mp="831.6" cp="1038.15" hpRegen="7.5" mpRegen="2.7" cpRegen="7.5" />
    <level value="62" hp="2123.11" mp="849.72" cp="1061.555" hpRegen="7.6" mpRegen="2.7" cpRegen="7.5" />
    <level value="63" hp="2170.23" mp="867.96" cp="1085.115" hpRegen="7.7" mpRegen="2.7" cpRegen="7.5" />
    <level value="64" hp="2217.66" mp="886.32" cp="1108.83" hpRegen="7.8" mpRegen="2.7" cpRegen="7.5" />
    <level value="65" hp="2265.4" mp="904.8" cp="1132.7" hpRegen="7.9" mpRegen="2.7" cpRegen="7.5" />
    <level value="66" hp="2313.45" mp="923.4" cp="1156.725" hpRegen="8.0" mpRegen="2.7" cpRegen="7.5" />
    <level value="67" hp="2361.81" mp="942.12" cp="1180.905" hpRegen="8.1" mpRegen="2.7" cpRegen="7.5" />
    <level value="68" hp="2410.48" mp="960.96" cp="1205.24" hpRegen="8.2" mpRegen="2.7" cpRegen="7.5" />
    <level value="69" hp="2459.46" mp="979.92" cp="1229.73" hpRegen="8.3" mpRegen="2.7" cpRegen="7.5" />
    <level value="70" hp="2508.75" mp="999.0" cp="1254.375" hpRegen="8.4" mpRegen="2.7" cpRegen="7.5" />
    <level value="71" hp="2558.35" mp="1018.2" cp="1279.175" hpRegen="8.5" mpRegen="3.0" cpRegen="8.5" />
    <level value="72" hp="2608.26" mp="1037.52" cp="1304.13" hpRegen="8.6" mpRegen="3.0" cpRegen="8.5" />
    <level value="73" hp="2658.48" mp="1056.96" cp="1329.24" hpRegen="8.7" mpRegen="3.0" cpRegen="8.5" />
    <level value="74" hp="2709.01" mp="1076.52" cp="1354.505" hpRegen="8.8" mpRegen="3.0" cpRegen="8.5" />
    <level value="75" hp="2759.85" mp="1096.2" cp="1379.925" hpRegen="8.9" mpRegen="3.0" cpRegen="8.5" />
    <level value="76" hp="2811.0" mp="1116.0" cp="1405.5" hpRegen="9.0" mpRegen="3.0" cpRegen="8.5" />
    <level value="77" hp="2862.46" mp="1135.92" cp="1431.23" hpRegen="9.1" mpRegen="3.0" cpRegen="8.5" />
    <level value="78" hp="2914.23" mp="1155.96" cp="1457.115" hpRegen="9.2" mpRegen="3.0" cpRegen="8.5" />
    <level value="79" hp="2966.31" mp="1176.12" cp="1483.155" hpRegen="9.3" mpRegen="3.0" cpRegen="8.5" />
    <level value="80" hp="3018.7" mp="1196.4" cp="1509.35" hpRegen="9.4" mpRegen="3.0" cpRegen="8.5" />
    <level value="81" hp="3071.4" mp="1216.8" cp="1535.7" hpRegen="9.5" mpRegen="3.0" cpRegen="8.5" />
    <level value="82" hp="3124.41" mp="1237.32" cp="1562.205" hpRegen="9.6" mpRegen="3.0" cpRegen="8.5" />
    <level value="83" hp="3177.73" mp="1257.96" cp="1588.865" hpRegen="9.7" mpRegen="3.0" cpRegen="8.5" />
    <level value="84" hp="3231.36" mp="1278.72" cp="1615.68" hpRegen="9.8" mpRegen="3.0" cpRegen="8.5" />
    <level value="85" hp="3285.3" mp="1299.6" cp="1642.65" hpRegen="9.9" mpRegen="3.0" cpRegen="8.5" />
</classInfo>

=== JoeAlisson/Server-Interlude/Datapack/data/xml/classes/HumanFighter.xml
<?xml version='1.0' encoding='utf-8'?>
<classInfo classId="0" name="Human Fighter" classLevel="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../schema/classInfo.xsd">
    <level value="1"   hp="80"      mp="30"     cp="32"      hpRegen="2.0"  mpRegen="0.9" cpRegen="2.0" />
    <level value="2"   hp="91.83"   mp="35.46"  cp="36.732"  hpRegen="2.05" mpRegen="0.9" cpRegen="2.0"/>
    <level value="3"   hp="103.79"  mp="40.98"  cp="1.516"   hpRegen="2.1"  mpRegen="0.9" cpRegen="2.0"/>
    <level value="4"   hp="115.88"  mp="46.56"  cp="6.352"   hpRegen="2.15" mpRegen="0.9" cpRegen="2.0"/>
    <level value="5"   hp="128.1"   mp="52.2"   cp="1.24"    hpRegen="2.2"  mpRegen="0.9" cpRegen="2.0"/>
    <level value="6"   hp="140.45"  mp="57.9"   cp="6.18"    hpRegen="2.25" mpRegen="0.9" cpRegen="2.0"/>
    <level value="7"   hp="152.93"  mp="63.66"  cp="1.172"   hpRegen="2.3"  mpRegen="0.9" cpRegen="2.0"/>
    <level value="8"   hp="165.54"  mp="69.48"  cp="6.216"   hpRegen="2.35" mpRegen="0.9" cpRegen="2.0"/>
    <level value="9"   hp="178.28"  mp="75.36"  cp="1.312"   hpRegen="2.4"  mpRegen="0.9" cpRegen="2.0"/>
    <level value="10"  hp="191.15"  mp="81.3"   cp="6.46"    hpRegen="2.45" mpRegen="0.9" cpRegen="2.0"/>
    <level value="11"  hp="204.15"  mp="87.3"   cp="1.66"    hpRegen="2.5"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="12"  hp="217.28"  mp="93.36"  cp="6.912"   hpRegen="2.6"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="13"  hp="230.54"  mp="99.48"  cp="2.216"   hpRegen="2.7"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="14"  hp="243.93"  mp="105.66" cp="7.572"   hpRegen="2.8"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="15"  hp="257.45"  mp="111.9"  cp="02.98"   hpRegen="2.9"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="16"  hp="271.1"   mp="118.2"  cp="08.44"   hpRegen="3.0"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="17"  hp="284.88"  mp="124.56" cp="13.952"  hpRegen="3.1"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="18"  hp="298.79"  mp="130.98" cp="19.516"  hpRegen="3.2"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="19"  hp="312.83"  mp="137.46" cp="25.132"  hpRegen="3.3"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="20"  hp="327.0"   mp="144.0"  cp="30.8"    hpRegen="3.4"  mpRegen="1.2" cpRegen="2.5"/>
    <level value="21"  hp="341.3"   mp="150.6"  cp="36.52"   hpRegen="3.5"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="22"  hp="355.73"  mp="157.26" cp="42.292"  hpRegen="3.6"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="23"  hp="370.29"  mp="163.98" cp="48.116"  hpRegen="3.7"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="24"  hp="384.98"  mp="170.76" cp="53.992"  hpRegen="3.8"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="25"  hp="399.8"   mp="177.6"  cp="159.92"  hpRegen="3.9"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="26"  hp="414.75"  mp="184.5"  cp="165.9"   hpRegen="4.0"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="27"  hp="429.83"  mp="191.46" cp="171.932" hpRegen="4.1"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="28"  hp="445.04"  mp="198.48" cp="178.016" hpRegen="4.2"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="29"  hp="460.38"  mp="205.56" cp="184.152" hpRegen="4.3"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="30"  hp="475.85"  mp="212.7"  cp="190.34"  hpRegen="4.4"  mpRegen="1.5" cpRegen="3.5"/>
    <level value="31"  hp="491.45"  mp="219.9"  cp="196.58"  hpRegen="4.5"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="32"  hp="507.18"  mp="227.16" cp="202.872" hpRegen="4.6"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="33"  hp="523.04"  mp="234.48" cp="209.216" hpRegen="4.7"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="34"  hp="539.03"  mp="241.86" cp="215.612" hpRegen="4.8"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="35"  hp="555.15"  mp="249.3"  cp="222.06"  hpRegen="4.9"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="36"  hp="571.4"   mp="256.8"  cp="228.56"  hpRegen="5.0"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="37"  hp="587.78"  mp="264.36" cp="235.112" hpRegen="5.1"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="38"  hp="604.29"  mp="271.98" cp="241.716" hpRegen="5.2"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="39"  hp="620.93"  mp="279.66" cp="248.372" hpRegen="5.3"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="40"  hp="637.7"   mp="287.4"  cp="255.08"  hpRegen="5.4"  mpRegen="1.8" cpRegen="4.5"/>
    <level value="41"  hp="654.6"   mp="295.2"  cp="261.84"  hpRegen="5.5"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="42"  hp="671.63"  mp="303.06" cp="268.652" hpRegen="5.6"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="43"  hp="688.79"  mp="310.98" cp="275.516" hpRegen="5.7"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="44"  hp="706.08"  mp="318.96" cp="282.432" hpRegen="5.8"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="45"  hp="723.5"   mp="327.0"  cp="289.4"   hpRegen="5.9"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="46"  hp="741.05"  mp="335.1"  cp="296.42"  hpRegen="6.0"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="47"  hp="758.73"  mp="343.26" cp="303.492" hpRegen="6.1"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="48"  hp="776.54"  mp="351.48" cp="310.616" hpRegen="6.2"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="49"  hp="794.48"  mp="359.76" cp="317.792" hpRegen="6.3"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="50"  hp="812.55"  mp="368.1"  cp="325.02"  hpRegen="6.4"  mpRegen="2.1" cpRegen="5.5"/>
    <level value="51"  hp="830.75"  mp="376.5"  cp="332.3"   hpRegen="6.5"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="52"  hp="849.08"  mp="384.96" cp="339.632" hpRegen="6.6"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="53"  hp="867.54"  mp="393.48" cp="347.016" hpRegen="6.7"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="54"  hp="886.13"  mp="402.06" cp="354.452" hpRegen="6.8"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="55"  hp="904.85"  mp="410.7"  cp="361.94"  hpRegen="6.9"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="56"  hp="923.7"   mp="419.4"  cp="369.48"  hpRegen="7.0"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="57"  hp="942.68"  mp="428.16" cp="377.072" hpRegen="7.1"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="58"  hp="961.79"  mp="436.98" cp="384.716" hpRegen="7.2"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="59"  hp="981.03"  mp="445.86" cp="392.412" hpRegen="7.3"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="60"  hp="1000.4"  mp="454.8"  cp="400.16"  hpRegen="7.4"  mpRegen="2.4" cpRegen="6.5"/>
    <level value="61"  hp="1019.9"  mp="463.8"  cp="407.96"  hpRegen="7.5"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="62"  hp="1039.53" mp="472.86" cp="415.812" hpRegen="7.6"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="63"  hp="1059.29" mp="481.98" cp="423.716" hpRegen="7.7"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="64"  hp="1079.18" mp="491.16" cp="431.672" hpRegen="7.8"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="65"  hp="1099.2"  mp="500.4"  cp="439.68"  hpRegen="7.9"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="66"  hp="1119.35" mp="509.7"  cp="447.74"  hpRegen="8.0"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="67"  hp="1139.63" mp="519.06" cp="455.852" hpRegen="8.1"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="68"  hp="1160.04" mp="528.48" cp="464.016" hpRegen="8.2"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="69"  hp="1180.58" mp="537.96" cp="472.232" hpRegen="8.3"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="70"  hp="1201.25" mp="547.5"  cp="480.5"   hpRegen="8.4"  mpRegen="2.7" cpRegen="7.5"/>
    <level value="71"  hp="1222.05" mp="557.1"  cp="488.82"  hpRegen="8.5"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="72"  hp="1242.98" mp="566.76" cp="497.192" hpRegen="8.6"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="73"  hp="1264.04" mp="576.48" cp="505.616" hpRegen="8.7"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="74"  hp="1285.23" mp="586.26" cp="514.092" hpRegen="8.8"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="75"  hp="1306.55" mp="596.1"  cp="522.62"  hpRegen="8.9"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="76"  hp="1328.0"  mp="606.0"  cp="531.2"   hpRegen="9.0"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="77"  hp="1349.58" mp="615.96" cp="539.832" hpRegen="9.1"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="78"  hp="1371.29" mp="625.98" cp="548.516" hpRegen="9.2"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="79"  hp="1393.13" mp="636.06" cp="557.252" hpRegen="9.3"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="80"  hp="1415.1"  mp="646.2"  cp="566.04"  hpRegen="9.4"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="81"  hp="1437.2"  mp="656.4"  cp="574.88"  hpRegen="9.5"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="82"  hp="1459.43" mp="666.66" cp="583.772" hpRegen="9.6"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="83"  hp="1481.79" mp="676.98" cp="592.716" hpRegen="9.7"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="84"  hp="1504.28" mp="687.36" cp="601.712" hpRegen="9.8"  mpRegen="3.0" cpRegen="8.5"/>
    <level value="85"  hp="1526.9"  mp="697.8"  cp="610.76"  hpRegen="9.9"  mpRegen="3.0" cpRegen="8.5"/>
</classInfo>

=== JoeAlisson/Server-Interlude/Datapack/data/xml/stats/classes/DwarfFighter.xml
<?xml version='1.0' encoding='utf-8'?>

<classInfo classId="53" name="Dwarf Fighter" classLevel="1"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org classInfo.xsd">
    <level value="1" hp="80.0" mp="30.0" cp="56.0" hpRegen="2.0" mpRegen="0.9" cpRegen="2.0" />
    <level value="2" hp="92.74" mp="35.46" cp="64.918" hpRegen="2.05" mpRegen="0.9" cpRegen="2.0" />
    <level value="3" hp="105.62" mp="40.98" cp="73.934" hpRegen="2.1" mpRegen="0.9" cpRegen="2.0" />
    <level value="4" hp="118.64" mp="46.56" cp="83.048" hpRegen="2.15" mpRegen="0.9" cpRegen="2.0" />
    <level value="5" hp="131.8" mp="52.2" cp="92.26" hpRegen="2.2" mpRegen="0.9" cpRegen="2.0" />
    <level value="6" hp="145.1" mp="57.9" cp="101.57" hpRegen="2.25" mpRegen="0.9" cpRegen="2.0" />
    <level value="7" hp="158.54" mp="63.66" cp="110.978" hpRegen="2.3" mpRegen="0.9" cpRegen="2.0" />
    <level value="8" hp="172.12" mp="69.48" cp="120.484" hpRegen="2.35" mpRegen="0.9" cpRegen="2.0" />
    <level value="9" hp="185.84" mp="75.36" cp="130.088" hpRegen="2.4" mpRegen="0.9" cpRegen="2.0" />
    <level value="10" hp="199.7" mp="81.3" cp="139.79" hpRegen="2.45" mpRegen="0.9" cpRegen="2.0" />
    <level value="11" hp="213.7" mp="87.3" cp="149.59" hpRegen="2.5" mpRegen="1.2" cpRegen="2.5" />
    <level value="12" hp="227.84" mp="93.36" cp="159.488" hpRegen="2.6" mpRegen="1.2" cpRegen="2.5" />
    <level value="13" hp="242.12" mp="99.48" cp="169.484" hpRegen="2.7" mpRegen="1.2" cpRegen="2.5" />
    <level value="14" hp="256.54" mp="105.66" cp="179.578" hpRegen="2.8" mpRegen="1.2" cpRegen="2.5" />
    <level value="15" hp="271.1" mp="111.9" cp="189.77" hpRegen="2.9" mpRegen="1.2" cpRegen="2.5" />
    <level value="16" hp="285.8" mp="118.2" cp="200.06" hpRegen="3.0" mpRegen="1.2" cpRegen="2.5" />
    <level value="17" hp="300.64" mp="124.56" cp="210.448" hpRegen="3.1" mpRegen="1.2" cpRegen="2.5" />
    <level value="18" hp="315.62" mp="130.98" cp="220.934" hpRegen="3.2" mpRegen="1.2" cpRegen="2.5" />
    <level value="19" hp="330.74" mp="137.46" cp="231.518" hpRegen="3.3" mpRegen="1.2" cpRegen="2.5" />
    <level value="20" hp="346.0" mp="144.0" cp="242.2" hpRegen="3.4" mpRegen="1.2" cpRegen="2.5" />
    <level value="21" hp="361.4" mp="150.6" cp="252.98" hpRegen="3.5" mpRegen="1.5" cpRegen="3.5" />
    <level value="22" hp="376.94" mp="157.26" cp="263.858" hpRegen="3.6" mpRegen="1.5" cpRegen="3.5" />
    <level value="23" hp="392.62" mp="163.98" cp="274.834" hpRegen="3.7" mpRegen="1.5" cpRegen="3.5" />
    <level value="24" hp="408.44" mp="170.76" cp="285.908" hpRegen="3.8" mpRegen="1.5" cpRegen="3.5" />
    <level value="25" hp="424.4" mp="177.6" cp="297.08" hpRegen="3.9" mpRegen="1.5" cpRegen="3.5" />
    <level value="26" hp="440.5" mp="184.5" cp="308.35" hpRegen="4.0" mpRegen="1.5" cpRegen="3.5" />
    <level value="27" hp="456.74" mp="191.46" cp="319.718" hpRegen="4.1" mpRegen="1.5" cpRegen="3.5" />
    <level value="28" hp="473.12" mp="198.48" cp="331.184" hpRegen="4.2" mpRegen="1.5" cpRegen="3.5" />
    <level value="29" hp="489.64" mp="205.56" cp="342.748" hpRegen="4.3" mpRegen="1.5" cpRegen="3.5" />
    <level value="30" hp="506.3" mp="212.7" cp="354.41" hpRegen="4.4" mpRegen="1.5" cpRegen="3.5" />
    <level value="31" hp="523.1" mp="219.9" cp="366.17" hpRegen="4.5" mpRegen="1.8" cpRegen="4.5" />
    <level value="32" hp="540.04" mp="227.16" cp="378.028" hpRegen="4.6" mpRegen="1.8" cpRegen="4.5" />
    <level value="33" hp="557.12" mp="234.48" cp="389.984" hpRegen="4.7" mpRegen="1.8" cpRegen="4.5" />
    <level value="34" hp="574.34" mp="241.86" cp="402.038" hpRegen="4.8" mpRegen="1.8" cpRegen="4.5" />
    <level value="35" hp="591.7" mp="249.3" cp="414.19" hpRegen="4.9" mpRegen="1.8" cpRegen="4.5" />
    <level value="36" hp="609.2" mp="256.8" cp="426.44" hpRegen="5.0" mpRegen="1.8" cpRegen="4.5" />
    <level value="37" hp="626.84" mp="264.36" cp="438.788" hpRegen="5.1" mpRegen="1.8" cpRegen="4.5" />
    <level value="38" hp="644.62" mp="271.98" cp="451.234" hpRegen="5.2" mpRegen="1.8" cpRegen="4.5" />
    <level value="39" hp="662.54" mp="279.66" cp="463.778" hpRegen="5.3" mpRegen="1.8" cpRegen="4.5" />
    <level value="40" hp="680.6" mp="287.4" cp="476.42" hpRegen="5.4" mpRegen="1.8" cpRegen="4.5" />
    <level value="41" hp="698.8" mp="295.2" cp="489.16" hpRegen="5.5" mpRegen="2.1" cpRegen="5.5" />
    <level value="42" hp="717.14" mp="303.06" cp="501.998" hpRegen="5.6" mpRegen="2.1" cpRegen="5.5" />
    <level value="43" hp="735.62" mp="310.98" cp="514.934" hpRegen="5.7" mpRegen="2.1" cpRegen="5.5" />
    <level value="44" hp="754.24" mp="318.96" cp="527.968" hpRegen="5.8" mpRegen="2.1" cpRegen="5.5" />
    <level value="45" hp="773.0" mp="327.0" cp="541.1" hpRegen="5.9" mpRegen="2.1" cpRegen="5.5" />
    <level value="46" hp="791.9" mp="335.1" cp="554.33" hpRegen="6.0" mpRegen="2.1" cpRegen="5.5" />
    <level value="47" hp="810.94" mp="343.26" cp="567.658" hpRegen="6.1" mpRegen="2.1" cpRegen="5.5" />
    <level value="48" hp="830.12" mp="351.48" cp="581.084" hpRegen="6.2" mpRegen="2.1" cpRegen="5.5" />
    <level value="49" hp="849.44" mp="359.76" cp="594.608" hpRegen="6.3" mpRegen="2.1" cpRegen="5.5" />
    <level value="50" hp="868.9" mp="368.1" cp="608.23" hpRegen="6.4" mpRegen="2.1" cpRegen="5.5" />
    <level value="51" hp="888.5" mp="376.5" cp="621.95" hpRegen="6.5" mpRegen="2.4" cpRegen="6.5" />
    <level value="52" hp="908.24" mp="384.96" cp="635.768" hpRegen="6.6" mpRegen="2.4" cpRegen="6.5" />
    <level value="53" hp="928.12" mp="393.48" cp="649.684" hpRegen="6.7" mpRegen="2.4" cpRegen="6.5" />
    <level value="54" hp="948.14" mp="402.06" cp="663.698" hpRegen="6.8" mpRegen="2.4" cpRegen="6.5" />
    <level value="55" hp="968.3" mp="410.7" cp="677.81" hpRegen="6.9" mpRegen="2.4" cpRegen="6.5" />
    <level value="56" hp="988.6" mp="419.4" cp="692.02" hpRegen="7.0" mpRegen="2.4" cpRegen="6.5" />
    <level value="57" hp="1009.04" mp="428.16" cp="706.328" hpRegen="7.1" mpRegen="2.4" cpRegen="6.5" />
    <level value="58" hp="1029.62" mp="436.98" cp="720.734" hpRegen="7.2" mpRegen="2.4" cpRegen="6.5" />
    <level value="59" hp="1050.34" mp="445.86" cp="735.238" hpRegen="7.3" mpRegen="2.4" cpRegen="6.5" />
    <level value="60" hp="1071.2" mp="454.8" cp="749.84" hpRegen="7.4" mpRegen="2.4" cpRegen="6.5" />
    <level value="61" hp="1092.2" mp="463.8" cp="764.54" hpRegen="7.5" mpRegen="2.7" cpRegen="7.5" />
    <level value="62" hp="1113.34" mp="472.86" cp="779.338" hpRegen="7.6" mpRegen="2.7" cpRegen="7.5" />
    <level value="63" hp="1134.62" mp="481.98" cp="794.234" hpRegen="7.7" mpRegen="2.7" cpRegen="7.5" />
    <level value="64" hp="1156.04" mp="491.16" cp="809.228" hpRegen="7.8" mpRegen="2.7" cpRegen="7.5" />
    <level value="65" hp="1177.6" mp="500.4" cp="824.32" hpRegen="7.9" mpRegen="2.7" cpRegen="7.5" />
    <level value="66" hp="1199.3" mp="509.7" cp="839.51" hpRegen="8.0" mpRegen="2.7" cpRegen="7.5" />
    <level value="67" hp="1221.14" mp="519.06" cp="854.798" hpRegen="8.1" mpRegen="2.7" cpRegen="7.5" />
    <level value="68" hp="1243.12" mp="528.48" cp="870.184" hpRegen="8.2" mpRegen="2.7" cpRegen="7.5" />
    <level value="69" hp="1265.24" mp="537.96" cp="885.668" hpRegen="8.3" mpRegen="2.7" cpRegen="7.5" />
    <level value="70" hp="1287.5" mp="547.5" cp="901.25" hpRegen="8.4" mpRegen="2.7" cpRegen="7.5" />
    <level value="71" hp="1309.9" mp="557.1" cp="916.93" hpRegen="8.5" mpRegen="3.0" cpRegen="8.5" />
    <level value="72" hp="1332.44" mp="566.76" cp="932.708" hpRegen="8.6" mpRegen="3.0" cpRegen="8.5" />
    <level value="73" hp="1355.12" mp="576.48" cp="948.584" hpRegen="8.7" mpRegen="3.0" cpRegen="8.5" />
    <level value="74" hp="1377.94" mp="586.26" cp="964.558" hpRegen="8.8" mpRegen="3.0" cpRegen="8.5" />
    <level value="75" hp="1400.9" mp="596.1" cp="980.63" hpRegen="8.9" mpRegen="3.0" cpRegen="8.5" />
    <level value="76" hp="1424.0" mp="606.0" cp="996.8" hpRegen="9.0" mpRegen="3.0" cpRegen="8.5" />
    <level value="77" hp="1447.24" mp="615.96" cp="1013.068" hpRegen="9.1" mpRegen="3.0" cpRegen="8.5" />
    <level value="78" hp="1470.62" mp="625.98" cp="1029.434" hpRegen="9.2" mpRegen="3.0" cpRegen="8.5" />
    <level value="79" hp="1494.14" mp="636.06" cp="1045.898" hpRegen="9.3" mpRegen="3.0" cpRegen="8.5" />
    <level value="80" hp="1517.8" mp="646.2" cp="1062.46" hpRegen="9.4" mpRegen="3.0" cpRegen="8.5" />
    <level value="81" hp="1541.6" mp="656.4" cp="1079.12" hpRegen="9.5" mpRegen="3.0" cpRegen="8.5" />
    <level value="82" hp="1565.54" mp="666.66" cp="1095.878" hpRegen="9.6" mpRegen="3.0" cpRegen="8.5" />
    <level value="83" hp="1589.62" mp="676.98" cp="1112.734" hpRegen="9.7" mpRegen="3.0" cpRegen="8.5" />
    <level value="84" hp="1613.84" mp="687.36" cp="1129.688" hpRegen="9.8" mpRegen="3.0" cpRegen="8.5" />
    <level value="85" hp="1638.2" mp="697.8" cp="1146.74" hpRegen="9.9" mpRegen="3.0" cpRegen="8.5" />
</classInfo>
